# Generated by Django 3.2.9 on 2021-12-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktodo',
            name='date',
            field=models.DateField(default='1997-09-29'),
            preserve_default=False,
        ),
    ]
